name = 'Vaporwave Terminal'
license = 'No rights reserved'
description = 'Vaporwave Terminal is a simple Hugo theme that evokes a bygone era of computer interaction. Blends enjoyable retro terminal aesthetics with modern minimal design.'
homepage = 'https://github.com/pavelnovel/web'
tags = ['retro', 'nostalgic','minimal']
features = ['simple']
[author]
  name = 'Pavel Konoplenko'
  homepage = 'https://pavelnovel.com'